### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by shansted** [2bbb/node-red-node-artnet#2]
TypeError: Cannot read property 'data' of undefined. 

Should var payload = msg.payload; actually be var payload = msg;

Otherwise i can not see how payload.data can exist? 

Thanks

**Comment by 2bbb** [comment]
@shansted 

thanks for issue.

i write payload format on README.
could you read that and check format please?

best regards

**Comment by shansted** [comment]
Actually turns out when installing from NPM , there is error in the code that you have already fixed "Fix Data". NPM must be pulling older version.
