### ISSUE TITLE
doesn't work in my installation, test-client works

### ISSUE THREAD

**Issue by jurischm** [2bbb/node-red-node-artnet#5]
hi,
I tried your node. somehow it doesn't work for me. the test-client.js works fine, but not in node red.

any suggestions? do you have a testflow which I can try to assure I don't mess up things with payload injection?

thanks and best,
michael

**Comment by 2bbb** [comment]
@jurischm 
hi.

at first, i don't know your environment.
please tell me your os, node-version.

where is `test-client.js` from?
if you check with original `artnet-node`'s `test-client.js`:
now i use forked `artnet-node` was customized. please check `2bbb/artnet-node`.

thanks
